### ISSUE TITLE
failed to open hkx file

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/HavokMax#1]
hi,

i try to use v1.4 open a hkx file but failed, could you help take a look this?

https://drive.google.com/file/d/1urm6DSVfM0WjklDENHOal2P1KF0mVAg-/view?usp=sharing

it also comes with a smd file that has mesh and skeleton

thanks!

**Comment by PredatorCZ** [comment]
The following file is in havok tagfile format.
You will need to convert it into packfile with assetcc or filter manager and use write to platform filter.
However, file contains multiple animations. Plugin loads only first so far.
File also doesn't contains bone name annotations. It could be loaded if havok skeleton would be loaded in a first place. If there is no skeleton in havok format, it would be impossible to load animations.
However this functionality is not yet implemented. I expected, that every animation uses annotations to lookup bones.

**Comment by redtankbai** [comment]
you are right, i do forgot submit skeleton file, here is the new one with mesh, skeleton and anim
https://drive.google.com/file/d/1DRreSzXf-xeYa_wA4PFlX8A_uU548aYU/view?usp=sharing
im not clear with how to "convert it into packfile with assetcc or filter manager and use write to platform filter", and details explain? thx!

**Comment by PredatorCZ** [comment]
Havok Filter Manager is a part of any Havok Content Tools package.
I recommend you to read Havok Content Tools User Guide for this.
AssetCC are command line apps, that converts between various Havok formats.
When you run these apps without arguments, it will print all information about how to use them.
AssetCC1 keeps toolset version for exported files, where AssetCC2 will always upgrades to current version.
Both of these app are stored inside BatchConvert folder, where Havok Tools are installed.
Just make sure, that you're using following commands: -s, -r

**Comment by PredatorCZ** [comment]
Following issue has been resolved for version 1.5.
