### ISSUE TITLE
3DS Max 2020 support

### ISSUE THREAD

**Issue by Skykila** [PredatorCZ/HavokMax#10]
Do you plan to support 3DS Max 2020?

**Comment by PredatorCZ** [comment]
Of course.

**Comment by guesswhosback1** [comment]
Hi, would like to know as well if the havok 3ds 2020 version would be available soon :D would be sooooooo appreciated !! thanks for your work btw !

**Comment by PredatorCZ** [comment]
It's almost a year since this request? Jeez. I hope I can roll it out this year.

**Comment by PredatorCZ** [comment]
Added in v1.11
