### ISSUE TITLE
Why a conjugation is needed for 3ds Max `Quat`

### ISSUE THREAD

**Issue by zoujyjs** [PredatorCZ/HavokMax#11]
I notice that both skeleton rotation and the animation keyframe rotation is conjugated. I tried to remove the conjugation but result in a flaw skeleton. 

But also the plugin for Noesis which also is right handed as 3ds Max, has no such operation. Is this a 3ds Max specific fixup or something mathmatic required? Because I see no reason to do so. Instead, since havok use a left handed system .we should use a transform matrix Sz to transform all the matrix into right handed coordinate system by Sz * T * Sz.

**Comment by PredatorCZ** [comment]
A quaternion conjugation (it's more known as quaternion tranposition) is a partial inversion of quaternion, where only inverted parts are the imaginary (i, j, k), where the real part (R) is intact.
It does have exact same effect as transposing a matrix.
Here is a image of what I mean. You can notice rows and columns are swapped.
![quattpp](https://user-images.githubusercontent.com/18037167/74267848-2212f900-4d07-11ea-83ac-53f23895f5cc.jpg)

It's not about whenever matrix is left or right handed. It's about the layout of matrix itself, and it's an API dependent.
For example OpenGL and DirectX are using different layouts.
Here is more info [http://www.mindcontrol.org/~hplus/graphics/matrix-layout.html](http://www.mindcontrol.org/~hplus/graphics/matrix-layout.html)

**Comment by zoujyjs** [comment]
That make sense! Thank you for your explanation!
