### ISSUE TITLE
Havok Content Tool (Havok Physics) Import/Export Support

### ISSUE THREAD

**Issue by Dash-POWER** [PredatorCZ/HavokMax#12]
Hi,
I have question regarding the HavokMax plugin. Will it support exporting havok physics (collisions, destruction data etc.) as well?

Thank you and have a nice day.

**Comment by PredatorCZ** [comment]
Do you mean official hkp shapes? HKC plugin already supports exporting. But only for some versions.

**Comment by Dash-POWER** [comment]
Yes. I meant if your plugin is able to export collisions and destruction without having the official Havok Content Tools for 3ds max.

**Comment by PredatorCZ** [comment]
You will still need official Havok tools in order to open scene files. Well you can open without them, but the custom Havok shapes won't work at all.
And no, my tool doesn't do that, it's focused on importing/exporting skeletons and animations.

**Comment by Dash-POWER** [comment]
Aha, ok. Thank you for explanation. :-)
