### ISSUE TITLE
Random infinite loading with no CPU usage upon import HKX

### ISSUE THREAD

**Issue by Amasiuncula** [PredatorCZ/HavokMax#16]
3ds max sometimes imports the 2010 hkx file with no problems, but sometimes puts the application into an endless loading cycle with no CPU usage.

Havok Content Tools PcXs 2014 has no problems with the target hkx file.

Tested on 3ds max 2018 and 2019, 64 bit, installed under C drive. Consistent problem.

I'm using the latest version of the plugin, tried older versions too, no good. Issue persists.

By helping me you will help my entire team about modding Witcher 3. We're currently working on a huge project that will import Bloodborne™ arsenal, enemies and animations into The Witcher 3.

I will leave the target skeleton & animation HKX files here! You're the only one who can help save the dreams of our team :)

Have a great day!
[Target.zip](https://github.com/PredatorCZ/HavokMax/files/4777135/Target.zip)

**Comment by PredatorCZ** [comment]
Try V1.11.1. There has been a lot of fixes, and it's working for me.

**Comment by Amasiuncula** [comment]
The update fixed! Works like a charm now. <3
