### ISSUE TITLE
Cannot import Havok animations that use lossless compression

### ISSUE THREAD

**Issue by 610kevinl** [PredatorCZ/HavokMax#19]
**Describe the bug**
Attempting to import .hkx animation files that were exported using lossless compression give the following error message:
ERROR: [Havok] Unregistered animation format.

**File information**
The animation files come from Fallout 4.

[animations.zip](https://github.com/PredatorCZ/HavokMax/files/5576793/animations.zip)
[skeleton.zip](https://github.com/PredatorCZ/HavokMax/files/5576794/skeleton.zip)

**3DS Max version**
3DS Max 2013 x64

** Havok version **
2014.1.0-r1

**Plugin version**
Tested using plugin v1.11.

**Comment by PredatorCZ** [comment]
I hesitated first to add support for it, since it's a custom class type, but eventually, I added support for it in V1.12.

**Comment by 610kevinl** [comment]
That’s great news! Is that build publically available yet? I have a bunch of animations I can test importing with if you need help with testing a new build. 😃 

Kevin

**Comment by PredatorCZ** [comment]
Yeah, that version is already available.

**Comment by 610kevinl** [comment]
That’s great, I will give the new version a try shortly. Thanks for all your work on this plugin. It’s tools like this that make game modding possible. 😃

**Comment by 610kevinl** [comment]
This issue was fixed (very promptly) in v1.12. Thanks Lukas!
