### ISSUE TITLE
deal with multi take hkx anim

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/HavokMax#2]
hi,

i got 1.5 and can load multi take anim now.
but the same question with RevilMax anim, is there a way to do batch process?
any tool can seperate hkx into single take?
or can assign motion id through script or ini settings other than ui when import?

thanks!

**Comment by PredatorCZ** [comment]
This setting is not exposed in .ini file.
You can convert hkx into xml file, and split animations with bindings by hand into separate files.
However such procedure would be tedious and take way more time than importing by hand.
There is no other way so far.

**Comment by redtankbai** [comment]
so could we try make settings can be set in .ini file? or an alt solution could be do that in noesis plugin, because noesis supports multi take fbx export

**Comment by PredatorCZ** [comment]
Request has been added to V1.6.
Variable is now exposed in .ini file.
Just be careful not to overflow index.

**Comment by redtankbai** [comment]
it's working perfect after test, nice job!
could same feature been applied on Revil plugin?

**Comment by PredatorCZ** [comment]
You must create issue there, I will not discuss on projects, that are not designated into their repo.
