### ISSUE TITLE
I wish HavokMax will have support Havok 2018

### ISSUE THREAD

**Issue by deercg** [PredatorCZ/HavokMax#22]
![](https://i.snipboard.io/GKnCRh.jpg)
Trying to import hkx but it's saying `Invalid version: 2018`. I used 3ds Max 2022. Is there a way that I can do to import hkx with this version? Thank you.

File example: [hkx_compendium.zip](https://github.com/PredatorCZ/HavokMax/files/8402233/hkx_compendium.zip)

**Comment by deercg** [comment]
@PredatorCZ

**Comment by PredatorCZ** [comment]
I don't know when 2018 support will be added, since only samples I have are so called compendium files used only in From Soft. engine. Compendium are not supported since they are specific and Idk if it's worth to add. Especially to 3ds max.
Gonna need to think about it.

**Comment by deercg** [comment]
Yes, @PredatorCZ. Thank you for view and let me know about this. You're right, I'm trying to import file of From Software's game called Elden Ring. Since your plugin work well with Dark Souls series, so I think you will know about this.
