### ISSUE TITLE
[Script] How To Call HavokMax in Maxscript Or Python?

### ISSUE THREAD

**Issue by heylenz** [PredatorCZ/HavokMax#23]
hi, How do I call a command in a script to do batch conversions?

**Comment by PredatorCZ** [comment]
Hi, with 3ds max there is only one way to do batch import/export.
There are maxscript functions called **importFile** and **exportFile**.
More here http://help.autodesk.com/view/3DSMAX/2017/ENU/?guid=__files_GUID_624D3D05_B15D_4A97_9F15_DA35CDB0DDD2_htm

**Comment by heylenz** [comment]
thanks
I can use importFile "skeleton.hkx" #noPrompt to cancle the interface.
