### ISSUE TITLE
Plugin not working with skyrim/skyrim se/fallout 4 hkx files (havok 2010 and 2014)

### ISSUE THREAD

**Issue by cesm1980** [PredatorCZ/HavokMax#3]
Not sure if this is something that happens only in studio max 2012 (the only one i can test the plugin) but any hkx file from skyrim i try to import it makes studio max crash with the following error :

---------------------------
Application Error
---------------------------
An error has occurred and the application will now close.
No scene changes have occurred since your last save.
---------------------------
OK   
---------------------------

Sometimes the import dialog appears, others it makes studio max 2012 crash right away, i tried both 32bit and 64bit plugins, exactly the same result.

Sure, i know there's alternative tools to import animations from skyrim in max, but the existing tools to convert hkx to kf were never completed, besides importing kf animations in max are always a nightmare because each time i try to import the same animation they aren't ever imported the same way, there's always some minor random glitches and i have no idea how to avoid this problem, so i am hoping there's some kind of alternative way to get animations from hkx files, since it's not just from skyrim i am interested, but other games using hkx.

Anyway which havok hkx versions your plugin is prepared for anyway? There's no mention of that on the instructions so i am completly in the dark about this, i don't even have any idea which games hkx files are supported or not, so at least tell me the hkx versions that are supported and if you know any games that are compatible.

By the way, the versions i tried are : hk_2010.2.0-r1 and hk_2014.1.0-r1.

note : i completly forgot to attach samples, altough confirm me if which versions are supported first

**Comment by PredatorCZ** [comment]
Both havok versions are supported. 
You must use 32bit plugin for 32bit application and vice versa. You mustn't use plugins with different versions or architecture than main program.
It's highly possible, that it's caused by some 3ds max old version shenanigans.
I cannot test older versions right now, it's a big task.
In the meantime, could you provide a minidump file with **_big** name suffix?

**Comment by cesm1980** [comment]
Sorry for the late answer :

> You must use 32bit plugin for 32bit application and vice versa. You mustn't use plugins with different versions or architecture than main program.

No no, i got that right, i just haven't detailed that what i actually did was that i tried the 32bit plugin with the 32bit version of max, and the 64bit plugin with the 64bit version of max, both having same results, so the problem wasn't there, so i keep using only the 64bit versions now.

> Both havok versions are supported.

Yeah, indeed, in the 2010 version i think i got this working finally, kinda, i had to read your thread on xentax and noticed we have to first load a skeleton for this to work (can you please resume the workflow process here too? Unless the other one is the complete and correct one), the skeleton apparently imports perfectly, altough this time i tried a different animation file which didn't make max crash, but something's not right, since a duplicate skeleton is created, i tried to import the animation without importing the skeleton.hkx file first but nothing was imported and i saw a long line of "warning" strings in the listener window. I send in attachment some hkx files, the "skeleton.hkx" file is a human skeleton for these animations, the file "FNISSPa001.hkx" so far is the only hkx file i was able to load without crashing max, altough it's clearly glitchy because apparently there's a duplicate skeleton created and the limbs seem stretched, no idea what's wrong. The files FNISSPa008.hkx and idlegrave_01.hkx don't even load, they make max crash.

[files.zip](https://github.com/PredatorCZ/HavokMax/files/3347473/files.zip)

> It's highly possible, that it's caused by some 3ds max old version shenanigans. I cannot test older versions right now, it's a big task.

Yeah i understand, but since it didn't crash with the other file i tried maybe this isn't the problem. Nevertheless, try loading these files in your max version to see if it crashes there too.

> In the meantime, could you provide a minidump file with _big name suffix?

You mean, max's report when it crashes ? Altough the only files generated are "3dsmax_minidump.dmp" and "dmpuserinfo.xml" if it's not these you meant, tell me how to get that file. Not sure if you still need this, confirm me after testing the hkx files i sent.

**Comment by PredatorCZ** [comment]
Thanks for those, I was able to address said problems, hopefully all of them will be fixed soon.
About _big file, 3ds max docs said, it will generate them as-well, but I had never encountered them, they might be generated in debug version (which is impossible to obtain by anyone), so I would drop that option.
As for old max versions, I had tested few of them, and all of them worked great.

**Comment by cesm1980** [comment]
Ok, thanks a lot, there's more hkx files i will test later but for now i will wait until this gets fixed.

Can you confirm me, that the worflow is just first loading the skeleton.hkx and then afterwards loading another hkx ? I noticed too that if i try to create a new scene to try loading another skeleton, it makes max crash again, and i have to again enable the plugin again, yeah, because everytime max crash with this, the plugin always gets in "deferred" state and has to be manually loaded in the plugins dialog box, which is very annoying. Perhaps you can somehow also prepare the plugin to somehow work properly after a "new scene" so that i don't have to close and open max everytime i want to open a new skeleton.hkx file ? I hope it's not much work.

**Comment by PredatorCZ** [comment]
This is weird, I had tested a lot with new scenes and such, and was able to import/export things with plugin.
This plugin is also treated as utility, that means always loaded.
If you can import/export every time a new scene is triggered, I would ignore this.

And yes, you can import animations for different skeletons, but for these files, it will crash, I forgot implement something for animations.

**Comment by PredatorCZ** [comment]
Issues has been fixed in V1.6.
Please verify and close this, if everything is ok.

**Comment by cesm1980** [comment]
Yeah thanks, it's a lot better now, FNISSPa008 seems to be okay, but in FNISSPa001 there's some "jittering" on the arms and hands, not sure if you know what i mean, it's kinda like in certain frames they "shake" in a un-natural way, this is something similar that is seen with mo-caps animations that weren't cleaned-up. Apparently it's just on the arms and hands, i have checked the original animation in-game, and there's no such jitters.

By the way i have yet to test the fallout 4 ones too, i will later comment how it goes.

Regarding the duplicate skeleton thing just ignore it, your plugin is working ok on that, it's supposed to be like that since i didn't knew that the skeleton hkx files did contain 2 sets of skeletons, apparently the extra one is for ragdoll models so never mind, that part isn't a bug at all.

I found two more bugs but i think it's better creating separate issues for them to avoid writing too much stuff here, i hope there's no problem, after all, i presume you apreciate the feedback, in the near future i will be needing this tool a lot so later i will test even more files.

**Comment by PredatorCZ** [comment]
The jittering is caused by scale animations, its caused by interpolation between frames.
The interpolation bug is caused by 3ds max itself, because it uses different approach into scale composition, than Havok.
When you move frame slider by hand, you will notice no such thing.
I am not sure, why they are using scale animations in such a bad way, but it's Bethesda alright.

**Comment by cesm1980** [comment]
Yeah, but when i am using the usual skyrim hkx to kf convertion tools (to convert hkx to gamebryo animation file format) to convert the exact same hkx file indeed the tool complains about "non-uniform scaling found while processing '(name of bone)' (it gives the error for each of those bones using this kind of scaling, altough i am not sure exactly how the author of the tools deal with this, i think he disables that scaling.

Anyway there's nothing that can be done about this ? I tried exporting the animation to fbx and then reading on other 3d program and of course, the problem persists. Perhaps you could add some kind of option on the dialog box to disable the scaling ? Or maybe the jiterring can be manually fixed, perhaps the same way it's done to clean up mocap animations (i think it was something about animation curves, not sure since i haven't ever tried this). Unless i just delete the scaling keys on the dopesheet, not sure what to do, in your opinion any idea of what can be done apart from just deleting the scale animation keys ?

**Comment by PredatorCZ** [comment]
Unfortunetly this "bug" is being caused by switching -/+ scale values between frames. Pretty nasty shit.
Only thing I can do, is to add "Disable scale tracks" button.
Or I could invert negative scaling, since it shouldn't be used at all, anywhere...
AFAIK I haven't encounter such issue elsewhere.

**Comment by cesm1980** [comment]
Ok if possible add those two options then, one for disable scale tracks and one for invert negative scaling, you can also add the & shortcuts to those two options like this too, see my other issue ( #6), so that i can use ALT+(letter), and perhaps too saving their last value used on the .ini file, that would be great.

**Comment by PredatorCZ** [comment]
Added `Disable scale` checkbox in v1.9. 
Please check it and close this issue, if everything is ok.

**Comment by cesm1980** [comment]
Yeah, there's no doubt, without the scaling seems a lot better now, thanks! Let's hope there isn't issues with other animations, seems fine now, i will reopen later if i find any other problems.
