### ISSUE TITLE
Suggestion for improved keyboard accesibility

### ISSUE THREAD

**Issue by cesm1980** [PredatorCZ/HavokMax#6]
Ok, there's a few suggestions that i am sure will be appreciated, i am talking about adding keyboard shortcuts to the buttons on the dialog box using ALT + LETTER (for example if in the code you would change the label the button "Import" to "&Import" i would be able to trigger the button by pressing alt+i), my native language isn't english even tough i write well but i don't know exactly what to call these kind of keyboard shortcuts because they are triggered when the buttons have the & symbol when coding them.

The main suggestions of this kind would be for example :
&Import
&Cancel
&Scale - in this case by pressing alt+s the focus would "jump" to the textbox with the number
&Motion ID - same as above but for the corresponding textbos

Oh and also, put the first focus on the "Import" button, because i mainly use keyboard only to import the files so i would have to just move the mouse to "Import" and click there, without the & alternative, i have to press TAB 3 times to reach there and press ENTER, so just pressing ENTER to activate that button would be great.

I think you get the point, i do a lot of visual basic.net programming and i do a lot of stuff like this so i presume it's very simple, even tough i am not sure exactly how you created the plugin but i think this is something easy and fast to code, and changing the tab order of the controls so that the Import would be the 0 one so that it would be the first one with focus.

**Comment by PredatorCZ** [comment]
I am afraid, that simply adding & won't do anything.
I am using basic winapi, so it's a pretty low level stuff.
It would require some extensive research, since I had never worked with a keyboard inputs.
On the other hand, setting initial focus on the Import key is rather a trivial task, but again for pressing ENTER, I would need to implement keyboard inputs.
However, I myself wanted to implement this, so I plan to add this at some point.

**Comment by cesm1980** [comment]
That's perfectly fine, i understood, altough trust me, if you make the Import button have the first focus ENTER does work, because if i press TAB 3 times until the focus is on Import button, and if i press ENTER it DOES activate the button already because it has the focus, so you don't have to do anything about the ENTER button, it's already working, the problem is just the focus being on the text edit control so i have to press TAB 3 times, so yeah, it's just a matter of changing the initial focus to the button Import, that's already a good help then !

**Comment by PredatorCZ** [comment]
Implemented in v1.9, please check and close this issue, if everything is ok.

**Comment by cesm1980** [comment]
Yeah, MUCH better now, thanks a lot! Much more pratical now and "automation" friendly :D
