### ISSUE TITLE
Max Crash when import hkx anim

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/HavokMax#7]
Hi Predator,

See files here
https://drive.google.com/file/d/1PXjIsm6_oFUMSccRLp1f8R-d5TiuXNeb/view?usp=sharing

There are two files
skel012_biped_reference.hkx - skeleton, can be import with Havok Max with no problem
sk012_mmax_fby_cn_run.hkx - anim file

the issue happen when load anim file
if load skeleton first then animation file, most of time Max will crash, but I also get a result that Max not crash but skeleton has very large translation value after anim been applied
if load anim to empty scene, then will just show bunch of skeleton missing message

Please take a look this when you have time
Cheers!

**Comment by PredatorCZ** [comment]
This issue has been already fixed, please update to the latest version.

**Comment by redtankbai** [comment]
it fixed, thanks!
