### ISSUE TITLE
Crash literally in Crash Bandicoot Nsane Trilogy

### ISSUE THREAD

**Issue by LeonNepelius** [PredatorCZ/HavokMax#8]
If i load the behavior file (the file with skeleton) everything seems fine. But if i try to load an animation file (doesn't matter if empty project or not) it 3ds max will crash.
I don't know if it matters but i renamed the extension hka to hkx so i can choose it.
But there is still spline compressed animation and it seems to be supported so idk?

Skeleton: [http://www.mediafire.com/file/epuund75wk73hhb/BossC3Uka.hkx/file](url)
Animation: [http://www.mediafire.com/file/dwiik1uboujwazf/BossC3Uka.hka/file](url)

**Comment by PredatorCZ** [comment]
This seems to be a duplicate of #7.

**Comment by PredatorCZ** [comment]
Issue has been fixed in V1.10.
