### ISSUE TITLE
Failed to open ascii hkx file

### ISSUE THREAD

**Issue by redtankbai** [PredatorCZ/HavokMax#9]
**Describe the bug**
Improper file format window pop out when import these ascii hkx file
as shown in file, it should be havok 2012.2.0 version
maybe need convert to some other format before can be use by havokMax?
If yes, how to do it? Thanks!

**File information**
https://drive.google.com/file/d/1n_c4L41LTuaTT8HT3vBAbHGUFilqL16b/view?usp=sharing
skeleton.HKX - skeleton
a000_000210.hkx - animation

**3DS Max version**
3DS Max 2014 x64

**Plugin version**
1.10

**Comment by PredatorCZ** [comment]
HavokLib doesn't support loading of the ascii files, you will need to convert them into the binary packfile.
These are the ways to convert them.
1. Use Write to platform filter in HCT
2. assetcc -s -r=8101 xmlfile_path hkxfile_outpath

**Comment by redtankbai** [comment]
it works, thx
